### PR TITLE
add power_on as default-flase flag to jlink.flash() and jlink.flash_file()

### PR DESCRIPTION
**Pull request by charlesnicholson**
Allows for externally-powered devices to be flashed without the JLink device providing target power.

### CODE REVIEW

**Comment by charlesnicholson** [comment]
Hmm, looks like the Python3.7-dev build is broken?

https://travis-ci.org/square/pylink/jobs/352087704

```
$ python setup.py test
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    import pylink
  File "/home/travis/build/square/pylink/pylink/__init__.py", line 29, in <module>
    from .jlink import *
  File "/home/travis/build/square/pylink/pylink/jlink.py", line 2106
    @decorators.async
                    ^
SyntaxError: invalid syntax
The command "python setup.py test" exited with 1.
0.09s$ python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    import pylink
  File "/home/travis/build/square/pylink/pylink/__init__.py", line 29, in <module>
    from .jlink import *
  File "/home/travis/build/square/pylink/pylink/jlink.py", line 2106
    @decorators.async
                    ^
SyntaxError: invalid syntax
The command "python setup.py bdist_wheel" exited with 1.
```

**Comment by hkpeprah** [comment]
Hm, seems like something related to `pycodestyle`; I'll see if they're off the dev branch, and update the YAML; should probably not be using dev branches for testing anyway.

**Comment by sstallion** [comment]
@hkpeprah I'm surprised that we were apply power by default. I would expect this to be off by default given that if we apply power to a board that isn't expecting it, we could cause issues if the SEGGER pinout isn't followed exactly. FWIW, the larger ARM 20-pin header does not standardize power pins.

**Comment by hkpeprah** [comment]
This was an oversight on my part, since in the examples, it seems like I always put a call to `power_on()` before calling the flash method.  I'd be in favour of changing the default behaviour, with a bump to the minor number.

**Comment by sstallion** [comment]
SGTM. @charlesnicholson would you mind changing the default for this to `False` before merge?

**Comment by charlesnicholson** [comment]
Will do. Stay tuned!

**Comment by charlesnicholson** [comment]
PR updated with `power_on=False` as a default value, plus tests. Looks like the 3.7 stuff is still causing trouble though...

**Comment by hkpeprah** [comment]
Just merged in a fix to remove using the development branch, since it's unstable.  Rebase/merge should resolve the issue for you.

**Comment by hkpeprah** [comment]
Functional tests pass, so this seems safe to merge once the unit tests pass.

**Pull request merged**
