### PR TITLE
support running setup.py develop from other directories

### PR DESCRIPTION
**Pull request by jsiverskog**
this is useful to test changes to the package from another virtual
environment, for instance.

### CODE REVIEW

**Comment by hkpeprah** [comment]
Sorry about the late look here.  What scenario is this patch addressing?

**Comment by jsiverskog** [comment]
> Sorry about the late look here. What scenario is this patch addressing?

i have another project having pylink as a dependency in a virtual environment. i want to test changes to pylink while running it from the other virtual environment (by running `python /path/to/pylink/setup.py develop` in the virtual environment).

**Comment by hkpeprah** [comment]
Hm, so if my understand is correct, you run `setup.py` from your alternate project directory.  From my understanding, you can install your checkout as an editable using pip (e.g. `pip install -e <path/to/directory>`) which should resolve your issue; you can also put the explicit path in your project's `setup.py` as a development requirement, or the editable in your requirements file.  I think both of those would address the issue in a more Pythonic way.  Thoughts?

**Comment by jsiverskog** [comment]
> Hm, so if my understand is correct, you run `setup.py` from your alternate project directory. From my understanding, you can install your checkout as an editable using pip (e.g. `pip install -e <path/to/directory>`) which should resolve your issue; you can also put the explicit path in your project's `setup.py` as a development requirement, or the editable in your requirements file. I think both of those would address the issue in a more Pythonic way. Thoughts?

i wasn't aware of `pip install -e` - that absolutely covers my needs. thanks!

**Pull request closed without merging**
