### PR TITLE
Set maximum interface speed to 100 MHz

### PR DESCRIPTION
**Pull request by twam**
Maximum interface speeds of up to 100 MHz are supported by J-Link (see
https://www.segger.com/products/debug-probes/j-link/models/model-overview/).
If a J-Link does not supported a speed, it will returned an error.
Verified to work with 100 MHz on J-Link Ultra+.

### CODE REVIEW

**Comment by hkpeprah** [comment]
I see 50MHz as the max target speed on that page.

**Comment by sstallion** [comment]
Does the interface speed have an effect on SWO? It looks like the Ultra+
supports 100MHz SWO.

**Comment by hkpeprah** [comment]
Nope.  SWO speed is separate, and set when you call `swo_enable()`.

**Comment by sstallion** [comment]
@hkpeprah is there any reason why we would want to gate the value passed into `set_speed()`? Would it be better to just let the SDK deal with validation in the event we do encounter a device with a (much) higher max interface speed?

**Comment by hkpeprah** [comment]
I think I originally put it in to guard against developer-error, but you're right, we'll be told anyway, so given we have a guard against the lower bound, the developer will know that whatever value they passed is higher than the upper-bound if it errors without our check.  I would support removing the guard against the upper bound.

**Comment by sstallion** [comment]
@twam Does that sound like a reasonable compromise? If we remove the upper bounds checking, you can pass in anything you like, including 100 MHz 😁

**Comment by twam** [comment]
Sounds reasonable to me!

**Comment by twam** [comment]
Should I create/adapt a PR?

**Comment by sstallion** [comment]
If you have the time that would be great. Thanks!

**Comment by twam** [comment]
I'll try. :)

I'm not an Python DLL/Lib expert. If I set a speed to high I get an error:
```ERROR  JLINKARM_SetSpeed(2000000kHz): Maximum JTAG speed exceeded. Did you specify speed in Hz instead of kHz ?```
and also a dialog box from J-Link complaining.
Is there a way to get this information from the `self._dll.JLINKARM_SetSpeed(speed)` call, so that I can raise an error to have the same behaviour of the API as before?

**Comment by hkpeprah** [comment]
Ah whoops, there is not of way of seeing if the speed failed.  That would explain why I did it the way I did it currently.  I think your changes thus far are fine then, but I would put it to the 50MHz upper limit instead.  @sstallion Thoughts?

**Comment by hkpeprah** [comment]
You could call `.set_max_speed()`, then `.speed()`, then check that against the value as that would give you the upper bound, which would be more correct, though it would add extra calls.

**Comment by twam** [comment]
Thought about this as well, but the value return is often 'slightly' different.

**Comment by twam** [comment]
Changed speed to 50 MHz.

**Comment by twam** [comment]
@hkpeprah, @sstallion Any updates?

**Comment by sstallion** [comment]
> @hkpeprah, @sstallion Any updates?

Looks reasonable to me. @hkpeprah what do you think?

**Pull request merged**
