### PR TITLE
don't unload the dll on linux, it causes nondeterministic crashes.

### PR DESCRIPTION
**Pull request by charlesnicholson**

### CODE REVIEW

**Comment by hkpeprah** [comment]
LGTM

**Comment by charlesnicholson** [comment]
Any chance you could make a release of this? We're currently targeting a pylink SHA instead of a pypi release...

**Comment by hkpeprah** [comment]
Already did 😄 
https://github.com/square/pylink/releases/tag/v0.0.9
https://pypi.python.org/pypi/pylink-square

**Comment by charlesnicholson** [comment]
Thanks!

**Pull request merged**
