### PR TITLE
Fix load dll for arm

### PR DESCRIPTION
**Pull request by CodeChenL**
test by rock pi 4b plus on ubuntu20.04

### CODE REVIEW

**Comment by hkpeprah** [comment]
Could you give a specific test case for this? We have some tests in the `test_library.py` test file, so covering the case of when it should and should not be yielding ARM binaries would be good to ensure we're not breaking any current functionality.

**Comment by CodeChenL** [comment]
> Could you give a specific test case for this? We have some tests in the `test_library.py` test file, so covering the case of when it should and should not be yielding ARM binaries would be good to ensure we're not breaking any current functionality.



My English is not very good, ask how I get the ` test_ library. Py `, is it to me write?

**Comment by hkpeprah** [comment]
The current tests are here: https://github.com/square/pylink/blob/master/tests/unit/test_library.py#L804

**Comment by CodeChenL** [comment]
> The current tests are here: https://github.com/square/pylink/blob/master/tests/unit/test_library.py#L804
Windows PC：
image
Rock Pi：
image

**Comment by CodeChenL** [comment]
> The current tests are here: https://github.com/square/pylink/blob/master/tests/unit/test_library.py#L804

my english is not good,do i need to do anything else？

**Comment by hkpeprah** [comment]
Sorry for the late response here. What I mean is that I think you should add some new tests to that test file that cover the specific scenario your changes address. So for example, if you have a directory with both ARM and non-ARM DLLs, on a non-ARM platform (non-ARM built Python), it should return the non-ARM DLL, but on an ARM-based platform running under Python built for ARM, it should return the ARM DLL.

**Comment by CodeChenL** [comment]
> 

I get it, I'll try to get it when I'm free

**Pull request closed without merging**
